/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Character = IDL.Record({
  'traits' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'relationships' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addCharacter' : IDL.Func([Character], [], []),
  'deleteCharacter' : IDL.Func([IDL.Text], [], []),
  'getCharacterByName' : IDL.Func([IDL.Text], [Character], ['query']),
  'getCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
  'getSampleCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Character = IDL.Record({
    'traits' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'relationships' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addCharacter' : IDL.Func([Character], [], []),
    'deleteCharacter' : IDL.Func([IDL.Text], [], []),
    'getCharacterByName' : IDL.Func([IDL.Text], [Character], ['query']),
    'getCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
    'getSampleCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };